version: "3.8"

services:
  # Postgres service
  database:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data
  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    env_file: .env
  # Express service
  web:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - SECRET_KEY
    env_file: .env
    volumes:
      - .:/app/users
      - /app/users/node_modules

volumes:
  database:
